---
title: "README for the The Worldwide Bureaucracy Indicators (WWBI)"
author: "Josefina Silva"
format: html
editor: visual
---

## Introduction

The Worldwide Bureaucracy Indicators (WWBI) database is a unique cross-national dataset on public sector employment and wages that aims to fill an information gap, thereby helping researchers, development practitioners, and policymakers gain a better understanding of the personnel dimensions of state capability, the footprint of the public sector within the overall labor market, and the fiscal implications of the public sector wage bill. The dataset is derived from administrative data and household surveys, thereby complementing existing, expert perception-based approaches.

The WWBI dashboard provides and overview of the indicators and the user can interact with the different indicators and countries and then download a report in a word document.

## Data Availability

The data availability for this dashboard was extracted from: [https://datacatalog.worldbank.org/int/search/dataset/0038132/worldwide-bureaucracy-indicatorshttps://datacatalog.worldbank.org/int/search/dataset/0038132/worldwide-bureaucracy-indicators](https://datacatalog.worldbank.org/int/search/dataset/0038132/worldwide-bureaucracy-indicators "WWBI database")

## Instructions for Replicators

1.  
